apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-certificate
spec:
  secretName: tls-secret  # Имя для секрета с TLS-сертификатом
  dnsNames:
    - app.aiperi.online  # Ваш домен для сертификата
  issuerRef:
    name: letsencrypt-prod  # Имя кластерного выпускателя (ClusterIssuer)
    kind: ClusterIssuer
